/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Oni145
 */
public class Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form Mainframe
     */
    public Mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        playbutton = new javax.swing.JToggleButton();
        SETTINGS = new javax.swing.JToggleButton();
        leaderboard1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusCycleRoot(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playbutton.setBackground(new java.awt.Color(255, 102, 0));
        playbutton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        playbutton.setForeground(new java.awt.Color(0, 0, 0));
        playbutton.setText("PLAY");
        playbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playbuttonActionPerformed(evt);
            }
        });
        BG.add(playbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 560, 110));

        SETTINGS.setBackground(new java.awt.Color(255, 102, 0));
        SETTINGS.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        SETTINGS.setForeground(new java.awt.Color(0, 0, 0));
        SETTINGS.setText("SETTINGS");
        SETTINGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SETTINGSActionPerformed(evt);
            }
        });
        BG.add(SETTINGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 560, 120));

        leaderboard1.setBackground(new java.awt.Color(255, 102, 0));
        leaderboard1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        leaderboard1.setForeground(new java.awt.Color(0, 0, 0));
        leaderboard1.setText("LEADERBOARD");
        leaderboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboard1ActionPerformed(evt);
            }
        });
        BG.add(leaderboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 560, 120));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 78)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PIXEL PUZZLER");
        BG.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -70, 630, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oni145\\Downloads\\437570333_7404826169593932_5032808077547283771_n.png")); // NOI18N
        jLabel1.setText("jLabel1");
        BG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void playbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playbuttonActionPerformed
    Levelselect pi = new Levelselect ();
   dispose();
    pi.setVisible(true);
        
  
    }//GEN-LAST:event_playbuttonActionPerformed

    private void SETTINGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SETTINGSActionPerformed
         Settings pi = new Settings ();
   dispose();
    pi.setVisible(true);
    
    }//GEN-LAST:event_SETTINGSActionPerformed

    private void leaderboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboard1ActionPerformed
         Leaderboard pi = new Leaderboard ();
   dispose();
    pi.setVisible(true);
           
    }//GEN-LAST:event_leaderboard1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JToggleButton SETTINGS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton leaderboard1;
    private javax.swing.JToggleButton playbutton;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
